/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor.gui;

import conversor.clases.ConvertidorMoneda;
import javax.swing.JOptionPane;

public class ConversorMonedaGui extends javax.swing.JFrame {

    /**
     * Creates new form ConversorMonedaGui
     */
    public ConversorMonedaGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        encabezado = new javax.swing.JLabel();
        deMoneda = new javax.swing.JComboBox<>();
        aMoneda = new javax.swing.JComboBox<>();
        a = new javax.swing.JLabel();
        de = new javax.swing.JLabel();
        ingresoMoneda = new javax.swing.JTextField();
        salidaConversion = new javax.swing.JLabel();
        convertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        encabezado.setText("CONVERTIDOR DE MONEDAS");

        deMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos", "Dólar", "Euro", "Libras" }));
        deMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deMonedaActionPerformed(evt);
            }
        });

        aMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos", "Dólar", "Euro", "Libras" }));
        aMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMonedaActionPerformed(evt);
            }
        });

        a.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        a.setText("a");

        de.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        de.setText("De");

        ingresoMoneda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingresoMoneda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ingresoMoneda.setText("Ingrese Cantidad");
        ingresoMoneda.setToolTipText("");
        ingresoMoneda.setAutoscrolls(false);
        ingresoMoneda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        ingresoMoneda.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ingresoMoneda.setOpaque(true);
        ingresoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoMonedaActionPerformed(evt);
            }
        });

        salidaConversion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salidaConversion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        convertir.setText("CONVERTIR");
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(de)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a)
                        .addGap(12, 12, 12)
                        .addComponent(aMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salidaConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(encabezado)))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ingresoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a)
                    .addComponent(deMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(de))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salidaConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //accion Lista
    private void aMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMonedaActionPerformed

    }//GEN-LAST:event_aMonedaActionPerformed

    //Accion boton
    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
        // Recibo posicion moneda origen
        //Recibo posicion moneda destino
        //recibo monto
        int ubicacionOrigen = deMoneda.getSelectedIndex();
        int ubicacionDestino = aMoneda.getSelectedIndex();
        try {
            double valor = Double.valueOf(ingresoMoneda.getText());
            String origen = deMoneda.getItemAt(ubicacionOrigen);
            String destino = aMoneda.getItemAt(ubicacionDestino);
            System.out.println("De: " + origen + " a " + destino);
            convMoneda = new ConvertidorMoneda();
            //Genero la moneda y realizo la conversion
            salidaConversion.setText(convMoneda.conversion(origen, destino, valor) + " " + destino);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor ingresado no es válido. Debe ser un número decimal.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_convertirActionPerformed

    //Listado de Moneda de Origen
    private void deMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deMonedaActionPerformed
    }//GEN-LAST:event_deMonedaActionPerformed

    //accion para ingresar texto
    private void ingresoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoMonedaActionPerformed

    }//GEN-LAST:event_ingresoMonedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JComboBox<String> aMoneda;
    private javax.swing.JButton convertir;
    private javax.swing.JLabel de;
    private javax.swing.JComboBox<String> deMoneda;
    private javax.swing.JLabel encabezado;
    private javax.swing.JTextField ingresoMoneda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel salidaConversion;
    // End of variables declaration//GEN-END:variables
    private ConvertidorMoneda convMoneda;
}
